/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_datax_common_util_EnvUtils */

#ifndef _Included_com_taobao_datax_common_util_EnvUtils
#define _Included_com_taobao_datax_common_util_EnvUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_datax_common_util_EnvUtils
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_taobao_datax_common_util_EnvUtils_getEnv
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_taobao_datax_common_util_EnvUtils
 * Method:    putEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_common_util_EnvUtils_putEnv
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
