#include <stdlib.h>

/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_taobao_datax_common_util_EnvUtils.h"
/* Header for class com_taobao_datax_common_util_EnvUtils */

/*
 * Class:     com_taobao_datax_common_util_EnvUtils
 * Method:    getEnv
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_taobao_datax_common_util_EnvUtils_getEnv
  (JNIEnv *env, jclass jobject, jstring key) {
    const char* skey = env->GetStringUTFChars(key, 0);
    char* value = getenv(skey);
    if (!value) {
        value = "";
    }

    jstring ret = env->NewStringUTF(value);
    return ret;
  }

/*
 * Class:     com_taobao_datax_common_util_EnvUtils
 * Method:    putEnv
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_common_util_EnvUtils_putEnv
  (JNIEnv *env, jclass jobject, jstring key, jstring value) {
    const char* sKey = env->GetStringUTFChars(key, 0);
    const char* sValue = env->GetStringUTFChars(value, 0);

    return setenv(sKey, sValue, 1);
  }


