/**
 * (C) 2010-2011 Alibaba Group Holding Limited.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License 
 * version 2 as published by the Free Software Foundation. 
 * 
 */


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni */

#ifndef _Included_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
#define _Included_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
 * Method:    oracle_dumper_init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni_oracle_1dumper_1init
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jlong, jlong);

/*
 * Class:     com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
 * Method:    oracle_dumper_connect
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni_oracle_1dumper_1connect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
 * Method:    oracle_dumper_predump
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni_oracle_1dumper_1predump
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
 * Method:    oracle_dumper_dump
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni_oracle_1dumper_1dump
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
 * Method:    oracle_dumper_commit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni_oracle_1dumper_1commit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni
 * Method:    oracle_dumper_finish
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_taobao_datax_plugins_writer_oraclewriter_OracleWriterJni_oracle_1dumper_1finish
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
